### ISSUE TITLE
Adding some workflows and checks

### ISSUE THREAD

**Issue by toolifelesstocode** [EzarDev/eZaR#18]
## Summary
Creating workflows and checks for the repository. The following workflows should be added:

- [flake8](https://flake8.pycqa.org/en/latest/)
- [black](https://black.readthedocs.io/en/stable/index.html)
- [isort](https://pycqa.github.io/isort/)

Pre-commit.ci should work on pull requests, and the `flake8`, `isort`, and `black` workflows work on commit pushes.

**Comment by yusufadell** [comment]
I can do that
